### ISSUE TITLE
edit about-page with reference to Bridges project

### ISSUE THREAD

**Issue by jeborsel** [Wise-Badges/frontend#1]
Best to include a reference to Bridges in the about since Bridges is the actual Erasmus+ project, Wisebadges is a tool developed in this project..
Maybe put something like.: 
Wisebadges is a part of [Bridges](https://bridges.openrecognition.org/) a project funded by ...

&

Wisebadges as part of [Bridges](https://bridges.openrecognition.org/) is supported by a consortium of ....

**Comment by SarahVanDenBerghe** [comment]
Done!
